apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: manoharshetty507/course-website:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 5000
    targetPort: 5000
